apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: yiwen-capstone2-app
    app.kubernetes.io/instance: yiwen-capstone2-app-instance
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: yiwen-capstone2-app
spec:
  selector:
    app: yiwen-capstone2-app
  type: NodePort
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 3000
